language: python

python:
- 2.7
- 3.5

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

before_script:
- pip install -r requirements.txt

script:
- if [[ $TEST ]]; then python test/travisci_test.py $TEST; fi
- python test/travisci_test.py